# Generated by Django 4.1.7 on 2023-03-13 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='image/%Y', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 13), verbose_name='date'),
        ),
    ]
