# Generated by Django 4.1.7 on 2023-03-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20, verbose_name='IP-address')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publication', verbose_name='Publication')),
            ],
        ),
    ]
